name: Model Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Training Script
        run: |
          python demo.py  # Or specify a training script if separate

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v2
        with:
          name: trained-model
          path: best_model.pkl  # Modify this path as needed
